"""Add subjects disciplines table

Revision ID: 4d82a87cac4d
Revises: 84a562817a70
Create Date: 2021-06-14 19:37:30.775889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d82a87cac4d'
down_revision = '84a562817a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('platform_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platforms')
    # ### end Alembic commands ###
