"""Add subjects disciplines table

Revision ID: 7ebd867c4bab
Revises: 4d82a87cac4d
Create Date: 2021-06-14 19:38:42.560650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ebd867c4bab'
down_revision = '4d82a87cac4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'platforms', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platforms', type_='unique')
    # ### end Alembic commands ###
