"""Add subjects disciplines table

Revision ID: 84a562817a70
Revises: d8e86e257c56
Create Date: 2021-06-14 12:43:57.955948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a562817a70'
down_revision = 'd8e86e257c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects_disciplines_table', sa.Column('discipline_id', sa.Integer(), nullable=True))
    op.drop_constraint('subjects_disciplines_table_disciplines_id_fkey', 'subjects_disciplines_table', type_='foreignkey')
    op.create_foreign_key(None, 'subjects_disciplines_table', 'disciplines', ['discipline_id'], ['discipline_id'])
    op.drop_column('subjects_disciplines_table', 'disciplines_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects_disciplines_table', sa.Column('disciplines_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subjects_disciplines_table', type_='foreignkey')
    op.create_foreign_key('subjects_disciplines_table_disciplines_id_fkey', 'subjects_disciplines_table', 'disciplines', ['disciplines_id'], ['discipline_id'])
    op.drop_column('subjects_disciplines_table', 'discipline_id')
    # ### end Alembic commands ###
