"""Add users

Revision ID: 88a471e890df
Revises: f76d92c31cd4
Create Date: 2021-06-12 19:43:26.296038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a471e890df'
down_revision = 'f76d92c31cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.Column('psw', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('silent_mode', sa.Boolean(), nullable=True),
    sa.Column('adding_filters', sa.Boolean(), nullable=True),
    sa.Column('current_platform', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('chat_id'),
    sa.UniqueConstraint('psw')
    )
    op.create_table('disciplines_users_table',
    sa.Column('discipline_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.discipline_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    op.create_table('subjects_programs_table',
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], )
    )
    op.drop_table('association')
    op.add_column('programs', sa.Column('program_id_in_platform', sa.String(), nullable=True))
    op.add_column('programs', sa.Column('platform', sa.String(), nullable=True))
    op.create_unique_constraint('_program_unique_id', 'programs', ['program_id_in_platform', 'platform'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_program_unique_id', 'programs', type_='unique')
    op.drop_column('programs', 'platform')
    op.drop_column('programs', 'program_id_in_platform')
    op.create_table('association',
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], name='association_program_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], name='association_subject_id_fkey')
    )
    op.drop_table('subjects_programs_table')
    op.drop_table('disciplines_users_table')
    op.drop_table('users')
    # ### end Alembic commands ###
