"""Add user foreign keys

Revision ID: a757cb34f2b0
Revises: 88a471e890df
Create Date: 2021-06-12 20:07:11.804342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a757cb34f2b0'
down_revision = '88a471e890df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries_users_table',
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.country_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    op.create_table('institutes_users_table',
    sa.Column('institute_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institute_id'], ['institutes.institute_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    op.add_column('users', sa.Column('type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('funded', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'funded')
    op.drop_column('users', 'type')
    op.drop_table('institutes_users_table')
    op.drop_table('countries_users_table')
    # ### end Alembic commands ###
