"""Add degree model

Revision ID: c79a20236ef9
Revises: ebbc180c00e5
Create Date: 2021-06-15 01:25:47.073687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79a20236ef9'
down_revision = 'ebbc180c00e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('degrees',
    sa.Column('degree_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('degree_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('degrees_users_table',
    sa.Column('degree_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['degree_id'], ['degrees.degree_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('degrees_users_table')
    op.drop_table('degrees')
    # ### end Alembic commands ###
