"""Add subjects disciplines table

Revision ID: d8e86e257c56
Revises: a757cb34f2b0
Create Date: 2021-06-14 12:25:39.213933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8e86e257c56'
down_revision = 'a757cb34f2b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects_disciplines_table',
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('disciplines_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['disciplines_id'], ['disciplines.discipline_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], )
    )
    op.drop_constraint('subjects_discipline_fkey', 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'discipline')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('discipline', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subjects_discipline_fkey', 'subjects', 'disciplines', ['discipline'], ['discipline_id'])
    op.drop_table('subjects_disciplines_table')
    # ### end Alembic commands ###
