"""Add platform model

Revision ID: ebbc180c00e5
Revises: 7ebd867c4bab
Create Date: 2021-06-14 19:47:06.836381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbc180c00e5'
down_revision = '7ebd867c4bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disciplines', sa.Column('platform_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'disciplines', 'platforms', ['platform_id'], ['platform_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'disciplines', type_='foreignkey')
    op.drop_column('disciplines', 'platform_id')
    # ### end Alembic commands ###
