"""Initial

Revision ID: f76d92c31cd4
Revises: 
Create Date: 2021-06-10 20:33:58.211716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76d92c31cd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('country_id')
    )
    op.create_table('disciplines',
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('discipline_id')
    )
    op.create_table('institutes',
    sa.Column('institute_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('country', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country'], ['countries.country_id'], ),
    sa.PrimaryKeyConstraint('institute_id')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('discipline', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['discipline'], ['disciplines.discipline_id'], ),
    sa.PrimaryKeyConstraint('subject_id')
    )
    op.create_table('departments',
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('institute', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institute'], ['institutes.institute_id'], ),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_table('programs',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('department', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('funded', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['department'], ['departments.department_id'], ),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('association',
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.program_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.drop_table('programs')
    op.drop_table('departments')
    op.drop_table('subjects')
    op.drop_table('institutes')
    op.drop_table('disciplines')
    op.drop_table('countries')
    # ### end Alembic commands ###
